### ISSUE TITLE
đậu chưa bạn?

### ISSUE THREAD

**Issue by giangbimin** [trungtinhandsome/promotion_rules#1]
mình thấy cái này lưu cái discount của product chung bảng promotion mới đúng

**Comment by lytrungtin** [comment]
> mình thấy cái này lưu cái discount của product chung bảng promotion mới đúng

Ùm bạn, mà sao bạn biết link của mình ta... :D

**Comment by giangbimin** [comment]
mình tìm thử trên git á chữ logivan là ra nhiều bạn lắm

**Comment by lytrungtin** [comment]
haha cảm ơn bạn mình cũng mới xem thử... bạn đang làm ở bên này hả :D

**Comment by giangbimin** [comment]
mình review 2 ngày trước bạn
mình note cho bạn vài ý:
1.  tính giá thì bạn nên tách ra làm services riêng do nó phụ thuộc nhiều model
2. nên chú ý thế nào về OOP ví dụ bạn tạo class base làm bao đóng để kế thừa và handle errors

đây là câu bạn leader nhận xét về bài của mình bạn có thể rút kinh nghiệm
"code structure / OOP not good enough, hard to maintain / expand. No testing for each promotion rule"

**Comment by giangbimin** [comment]
mình mới false rồi

**Comment by lytrungtin** [comment]
mình cũng đc nhận comment nè 
“Your code is able to solve the problem of these specific cases but it is still not easy to maintain / expand. If we have more 10 promotion rules, and each has a different business case, the code should be able to adapt to it, when a promotion rule changes, it should not affect others.”

**Comment by giangbimin** [comment]
mình chưa tìm được bạn nào đậu để tham khảo coi. mình làm chỗ khác là Senior nhưng qua đây không đạt nên đang xem mình yếu ở đâu
cho dù mình có phản biện
I do not agree with his comment. I will explain why I use this code.
About Code Structure. I already used the service object to keep the model clean and easy to maintain.
OOP not good enough.
- In the model, I use Struct instead of Class because I don't need any method in the Object except initialize
Maintain and Expand
- I already used ServiceObject I can apply other structures like FormObject, ValueObject, Decorator to this project.

**Comment by tienthuan1412** [comment]
So sad :(

**Comment by trungtinhandsome** [comment]
Mình cũng chưa hiểu của mình sao mà:
"If we have more 10 promotion rules, and each has a different business case, the code should be able to adapt to it, when a promotion rule changes, it should not affect others."

**Comment by giangbimin** [comment]
bài này của bạn đậu pv nè: https://github.com/thiennguyenmark/logivan-solution-checkout/
bạn này OOP tốt. cách giải quyết bạn này khá giống mình nhưng mình thấy chưa tối ưu: lí do là mỗi lần add_product đều phải chạy lại code

nhận xét bên bạn nè:
- không nên viết logic trong test case chỉ có khởi tạo và thực thi so sánh kết quả thôi
- khi bạn muốn thêm 1 loại promotion type khác logic khác thì bạn xữ lí sao.

**Comment by lytrungtin** [comment]
ùm bạn, mình thấy mình không hợp với ROR nữa rồi :(

**Comment by tienthuan1412** [comment]
tạm biệt :(

**Comment by lytrungtin** [comment]
> khi bạn muốn thêm 1 loại promotion type khác logic khác thì bạn xữ lí sao.

Bạn ví dụ thực tế luôn được không
